### ISSUE TITLE
How does the console command work?

### ISSUE THREAD

**Issue by j-greig** [superbigco/craft-imagerpretransform#1]

**Comment by sjelfull** [comment]
`./craft help imager-pretransform/default/index`

To transform assets in a volume: 
`./craft imager-pretransform/default/index --volume=<volumeHandle> or -v <volumeHandle>`

To transform assets in a folder: 
`./craft imager-pretransform/default/index --folderId=<folder id>`

**Comment by piotrpog** [comment]
@sjelfull I tried this command on windows, like this:
`craft help imager-pretransform/default/index --volume=handle`

Console showed this error:
`Error: Unknown option: --volume`

For using -v alias, i got error:
`Error: Unknown alias: -v`

**Comment by sjelfull** [comment]
@piotrpog The first command just lists out information about the different parameters it expect. Note the `help` keyword. Remove that, and it should work.
