### ISSUE TITLE
Inject "index number of image" variable into template during pretransform

### ISSUE THREAD

**Issue by piotrpog** [superbigco/craft-imagerpretransform#10]
One of my clients wants his images to look like this - for seo pourposes:
`entry-name-n.extension`
where `n` is number of image, so first one assigned to entry has number 1, second 2 etc.
I dont really know how this can be achieved using pretransform right now - so i propose adding ner variable injected into template, index of image.

**Comment by sjelfull** [comment]
This is outside of the scope of this plugin.

You would need to make a custom plugin/module to handle this.
