### ISSUE TITLE
Some images are not transformed

### ISSUE THREAD

**Issue by piotrpog** [superbigco/craft-imagerpretransform#11]
I use plugin with console comand and template `do craft.imager.transformImage`.
When i run command, most images from specific asst source are not transformed, only some. Im not really sure what distingushes these that are nor transformed from these that are.

**Comment by sjelfull** [comment]
Since its working for some images, I assume the plugin is doing its thing, since it's just queue jobs and calls to Imager.

Did you find any errors in the log?

I would also look into Imager and its logs to see whats up.

**Comment by sjelfull** [comment]
Closing because of no response. Let me know if this happens again.
