### ISSUE TITLE
Config file containing only some asset sources = array expected error

### ISSUE THREAD

**Issue by cliveportman** [superbigco/craft-imagerpretransform#12]
The following error is returned when creating a config that contains instructions for some asset sources but not all. Uploading to an asset source not included in the config:
```
2019-03-05 16:49:44 [-][1][-][error][craft\queue\QueueLogBehavior::afterError]  [588] Pretransforming images (attempt: 1) - Error (time: 0.050s): Array to string conversion
2019-03-05 16:49:44 [-][1][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Array to string conversion in /home/hudson/vendor/aelvan/imager/src/helpers/ImagerHelpers.php:369
```

My fix was to ensure each asset source has instructions defined for it within the config file, and that a transform is specified for each one even if it isn't required. I think we should only need to add configs if they're needed.

No problems until I upload something to an asset source not included in the config (e.g. the 'work' assets source):
```
return [
    'transforms' => [
        'home' => [
            [
                'width' => 480,
                'mode' => 'fit',
                'jpegQuality' => 65
            ],
        ],
];
```

We're now fine because I've provided instructions and an image transform for the 'work' source (even though I don't need it):
```
return [
    'transforms' => [
        'home' => [
            [
                'width' => 480,
                'mode' => 'fit'
            ],
        'work' => [
            [
                'width' => 480,
                'mode' => 'fit'
            ],
        'press' => [
            [
                'width' => 480,
                'mode' => 'fit'
            ]
        ]
];
```

**Comment by sjelfull** [comment]
Thanks for reporting. I'll look into it.

**Comment by mattstein** [comment]
I've just run into this as well. It looks like the service's `getTransforms()` [can return the entire transform settings array](https://github.com/superbigco/craft-imagerpretransform/blob/master/src/services/ImagerPretransformService.php#L112-L116) and should somehow limit its return value to something resembling real transform settings.

If I swap the preceding volume handle check to bail if there simply isn't a volume handle with settings...

```php
if ($volumeHandle === null || empty($transforms[ $volumeHandle ]))
{
    return null;
}
```

...that solves this problem but obviously leaves out the option of using transforms that are applied globally and not by volume.

Maybe array items with string indexes *not* matching the current Asset Volume handle could be stripped from the returned value?

**Comment by mattstein** [comment]
FWIW @cliveportman, I can also get around this by listing transform-less volumes with empty two-level arrays:

```php
return [
    'transforms' => [
        'logos' => [[]],
        'general' => [[]],
        'icons' => [[]],
        'downloads' => [[]],
        /* ... */
```

Looks silly, but doesn't generate unnecessary transforms or result in any errors.

**Comment by sjelfull** [comment]
I will release a new version soon that:
- Allow a mix of global and volume specific transforms
- Filters out any volume transforms not related to the current volume

Hopefully this should resolve the problems you have reported here.
