### ISSUE TITLE
Image optimisation on resize [FEATURE]

### ISSUE THREAD

**Issue by Djive** [superbigco/craft-imagerpretransform#13]
It would be great if we could opt to optimise images on automatic resize on upload.
Does that exist already in the plugin?
If not, can it be implemented?

Thanks!

**Comment by sjelfull** [comment]
Could you clarify what you mean, and how you imagine it working?

**Comment by Djive** [comment]
main point is just to shrink size of images, as now even we resize  images they still have couple MB
instead 100kb

**Comment by Djive** [comment]
For example, Lossless compression instead of just reducing image quality by 50%

**Comment by sjelfull** [comment]
So Imager Pretransform just uses Imager under the hood and doesn't have anything do with the actual image processing. This sounds like you need to tweak your Imager transforms/settings?

**Comment by Djive** [comment]
Ok, thanks!
At the moment, we only have Interlacing set up on the Craft Assets Image Transforms.

**Comment by sjelfull** [comment]
No problem! Check out [Imager](https://github.com/aelvan/Imager-Craft)
