### ISSUE TITLE
[BUG] Console command fails with 'Source folder [path] does not exist'

### ISSUE THREAD

**Issue by meredevelopment** [superbigco/craft-imagerpretransform#16]
**Bug Description**
I have a local asset folder with handle `assetVolumeOne`, with 3 images in it.
If I clear transforms (either via 'Utilities > Clear Caches' or In the Assets GUI) then run the command: 
`./craft imager-pretransform/default/index --volume=assetVolumeOne` 

the result is: 
```
> Processing 3 images.
[=================================>                                                                  ] 33% (1/3) ETA: n/aException 'aelvan\imager\exceptions\ImagerException' with message 'Source folder “assets/assetVolumeOne” does not exist'

in /Users/ben/Sites/crafttest/vendor/aelvan/imager/src/transformers/CraftTransformer.php:207

Stack trace: [snip]
```

**Screenshots**

Volume setup 1:
![image](https://user-images.githubusercontent.com/3437528/61783981-bca9fa00-ae00-11e9-859c-91c97fdf6241.png)

Volume setup 2:
![image](https://user-images.githubusercontent.com/3437528/61784047-dd724f80-ae00-11e9-85e5-90ec06729d08.png)

Assets folder / GUI:
![image](https://user-images.githubusercontent.com/3437528/61784075-eebb5c00-ae00-11e9-8ee8-a3f058153d1b.png)

Console output:
![image](https://user-images.githubusercontent.com/3437528/61784477-ac464f00-ae01-11e9-9dd5-15e82f10b5a1.png)

**Additional context**

If I manually recreate all the transforms by selecting all image and using the 'Pretransform' function in the Assets GUI, the command then works. Presumably it sees the existing file and does nothing. 

I've tried hardcoding the Imager path with this `config/imager.php` but it makes no difference: 

```
return [
    'imagerSystemPath' => '/Users/ben/Sites/crafttest/web/imager',
];
```

This is my `imager-pretransform.php` config: 

```
return [
    'transforms' => [
        'assetVolumeOne' => [
            [
                'width' => 300,
            ],
            [
                'width' => 300,
                'effects' => [
                    'grayscale' => true,
                    'gamma'     => 1.5,
                ],    
            ],
            [
                'width' => 300,
                'effects' => [
                    'grayscale' => true,
                    'gamma'     => 3,
                ],
            ],
            [
                'width' => 300,
                'height' => 300,
                'jpegQuality' => 1,
                'mode' => crop,
                'position'    => 'top-left',
            ],
        ],
    ],
];
```

**Comment by sjelfull** [comment]
It looks like your using relative paths in your Volume settings. It's recommended you use [absolute paths](https://docs.craftcms.com/v3/assets.html#volumes) for this.

The way I usually set these is using environment variables.

**Comment by meredevelopment** [comment]
Ok thank you Fred, I've set an absolute path and it's working. Also tested with env var / alias, also working 👍

For others searching, here's what I did:

In '.env' I added: 
`ABSOLUTE_ROOT="/Full/path/to/my/crafttest"`

In 'config/general.php' `*` I added: 
```
'aliases' => [
            '@absoluteRoot' => getenv('ABSOLUTE_ROOT'),
],
```

In the Assets settings I set 'File System Path' to:
`@absoluteRoot/web/assets/assetVolumeOne`

To test the alias was working I put this in a twig template:
`@absoluteRoot: {{ alias('@absoluteRoot')}}`
