### ISSUE TITLE
[FEATURE] Webp support?

### ISSUE THREAD

**Issue by a-rbsn** [superbigco/craft-imagerpretransform#23]
I'm currently generating Webp through normal transforms — are webp transforms part of this plugin?

**Comment by sjelfull** [comment]
It just uses Imager under the hood, so whatever Imager supports works - including Webp.

https://github.com/aelvan/Imager-Craft/blob/e06b24885dd194a6b0659a66f9333067975b027e/README.md#webpimagickoptions-array
