### ISSUE TITLE
update required dependency imager to imager-x

### ISSUE THREAD

**Issue by yanickrecher** [superbigco/craft-imagerpretransform#24]
The current version of `imagepretransform` use the `imager` plugin. the plugin `imager` is abandoned and should not be used.

It would be good to use  the plugin `spacecatninja/imager-x`, which is a replacement if that is possible.

**Comment by sjelfull** [comment]
Imager X includes its own pretransform functionality, so i'm not sure that I see the need? https://imager-x.spacecat.ninja/usage/generate.html
