### ISSUE TITLE
Option to process command in jobs

### ISSUE THREAD

**Issue by riasvdv** [superbigco/craft-imagerpretransform#8]
I'm using async queue, and it would be a lot faster to have the console command spawn a job for each image instead of doing everything in one thread.

Could you add an option to have it do this?

**Comment by sjelfull** [comment]
Good idea. As always, an PR would be welcome :D And while your at it, you could time how much faster it is.

**Comment by sjelfull** [comment]
Included in 2.0.3. There is a new `processImagesInJobs` config option.
