### ISSUE TITLE
Ability to disable automatic pretransform

### ISSUE THREAD

**Issue by exophunk** [superbigco/craft-imagerpretransform#9]
Is there a way to disable the automatic job generation on image upload and only use the console command to pretransform images?

I am importing about 3000 images with Feed-Me and i dont want pretransform to happen on import, but to manually do it with your console command afterwards.

It would be nice if you could switch the automatic pretransforming on/off in either the config file or the plugin settings.

**Comment by sjelfull** [comment]
Not currently, other than to disable the plugin manually.

This is a good idea, but not likely I will have time to look at it for a while.

Feel free to submit a pull request that adds this.
